name: asrw

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.6

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Install necessary tools
      run: sudo apt-get update && sudo apt-get install -y wget default-jdk unzip
    
    - name: Install Nextflow
      run: |
        export NXF_VER=24.04.0-edge
        wget -qO- https://get.nextflow.io | bash
        chmod +x nextflow
        mv nextflow /usr/local/bin

    - name: Debug - Pull Docker Image
      run: docker pull ghcr.io/dennislarsson/download-image:download-into-folder-4ed51e5

    - name: Run test
      run: nextflow run main.nf -c nextflow.config --samples_json tests/test_samples.json --popmap tests/popmap_test
